_target_: src.datamodules.FineTuneDM.FineTuneDM

data_dir: ${data_dir} # data_dir is specified in config.yaml
train_val_test_split: "80_20_0"

batch_size: 8
num_workers: 3
pin_memory: True

arch: ${module.arch}
seq_len: ${module.seq_len}
cache_dir: ${data_dir}/cache

notes: "Fine tune data with bsz=${.batch_size}"