_target_: src.datamodules.OneVsOneDM.OneVsOneDM

data_dir: ${data_dir} # data_dir is specified in config.yaml
train_val_test_split: "80_20_0"

num_positives: 1
num_negatives: 6

batch_size: 2
num_workers: 3
pin_memory: True

arch: ${module.arch}
seq_len: ${module.seq_len}
cache_dir: ${data_dir}/cache

notes: "OneVsOne data with bsz=${.batch_size}"